In [1]:
import numpy as np

In [2]:
age = [18, 23, 40, 31, 28]
age_arr = np.array(age)
print(age_arr)
print(type(age_arr))

[18 23 40 31 28]
<class 'numpy.ndarray'>


In [3]:
np.random.random(size = 20)

array([0.92115777, 0.24140547, 0.04616474, 0.02488802, 0.17693692,
       0.7385059 , 0.04033636, 0.45724507, 0.81481914, 0.03180995,
       0.92183667, 0.20030181, 0.31690107, 0.81502459, 0.23817864,
       0.59899846, 0.20902954, 0.5534471 , 0.14701873, 0.91995213])

In [4]:
np.random.rand(2,4)

array([[0.94274233, 0.3446377 , 0.2142607 , 0.5519861 ],
       [0.30852207, 0.67184216, 0.70191488, 0.51693678]])

In [5]:
np.random.randn(3,3)

array([[ 5.46587934e-01,  2.18871807e-01,  2.12099181e+00],
       [-8.76916835e-01,  4.87644993e-04,  1.89696782e-01],
       [-1.17619231e+00,  1.36253016e+00,  1.32516364e-01]])

In [6]:
np.random.randint(2,9)

5

In [7]:
np.random.randint(1,100,10)

array([48, 31, 86, 64, 57, 47, 85, 56, 60, 16])

In [8]:
np.arange(10,40,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [9]:
np.linspace(1,100,10)
# np.linspace(1,100,10, dtype=int)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
# np.empty((3,3))
np.empty((3,3), dtype=int)

array([[4603098445975336441, 4597053708208775629, 4611958467759869078],
       [4606073784204089551, 4557631086035133874, 4596002567128517032],
       [4607975918408178461, 4608815109510148167, 4593942425460847561]])

In [13]:
np.full((3,3,), fill_value=24)

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [14]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.eye(N=5,M=5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [16]:
nums = np.array([(10,20,30), (12, 34, 56)])
print(nums.shape)
print(nums.size)
print(nums.dtype)
print(nums.ndim)

(2, 3)
6
int64
2


In [17]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
emp = np.array([('Charles',18), ('Logan',20), ('Jessica', 34)])
print(emp, '\n')
emp_reshaped = emp.reshape(6,1)
print(emp_reshaped)

[['Charles' '18']
 ['Logan' '20']
 ['Jessica' '34']] 

[['Charles']
 ['18']
 ['Logan']
 ['20']
 ['Jessica']
 ['34']]


In [19]:
print(emp[0])
print(emp[-1])
print(emp[0][1])

['Charles' '18']
['Jessica' '34']
18


In [20]:
weight = np.array([73, 68, 55.5, 43, 92, 66])
print(weight[3:5])
print(weight[::3])
print(weight[:3])

[43. 92.]
[73. 43.]
[73.  68.  55.5]


In [21]:
age = np.array([[73,68,54], [21,36,19]])
print(age[0, 0:2])
print(age[1, 1:3])

[73 68]
[36 19]


In [22]:
odd_num = np.array([1,5,9,15])
even_num = np.array([2,6,12,26])
sum = odd_num + even_num
sub = odd_num - even_num
multiplication = odd_num * 2
print(sum)
print(sub)
print(multiplication)

[ 3 11 21 41]
[ -1  -1  -3 -11]
[ 2 10 18 30]


In [23]:
#Hamadard Product
n1 = np.array([[1,0,2], [4,-2,3]])
n2 = np.array([[4,0,1], [2,3,0]])
prod = n1 * n2
print(n1, '\n')
print(n2, '\n')
print(prod)

[[ 1  0  2]
 [ 4 -2  3]] 

[[4 0 1]
 [2 3 0]] 

[[ 4  0  2]
 [ 8 -6  0]]


In [24]:
#Matrix Multiplication
m1 = np.array([[1,0,2], [4,-2,3]])
m2 = np.array([[4,0],[2,3], [1,4]])
multi = m1.dot(m2)
print(multi)

[[ 6  8]
 [15  6]]


In [25]:
salary = np.array([100000, 2000, 45000, 980000, 1000, 75500])
print("Max salary:", salary.max())
print("Min salary:", salary.min())
print("Variance:", salary.var())
print("Standard Deviation:", salary.std())

Max salary: 980000
Min salary: 1000
Variance: 122788034722.22223
Standard Deviation: 350411.23658099526


In [42]:
nums = np.array([1,2,3,4,5])
print(np.square(nums))
print(np.power(nums,3))

[ 1  4  9 16 25]
[  1   8  27  64 125]


In [27]:
print(emp)
print(emp.shape, '\n')
print(np.transpose(emp))
print(np.transpose(emp).shape)

[['Charles' '18']
 ['Logan' '20']
 ['Jessica' '34']]
(3, 2) 

[['Charles' 'Logan' 'Jessica']
 ['18' '20' '34']]
(2, 3)


In [28]:
#concatenate two 1D arrays
print(odd_num, even_num)
all_nums = np.concatenate([odd_num, even_num])
print(all_nums)

[ 1  5  9 15] [ 2  6 12 26]
[ 1  5  9 15  2  6 12 26]


In [29]:
#concatenate two 2D arrays
data_scientists = np.array([('Charles',18), ('Logan',20), ('Jessica', 34)])
consultants = np.array([('Jean', 21), ('Phoenix', 20)])
employees = np.concatenate([data_scientists, consultants])
print(employees)

[['Charles' '18']
 ['Logan' '20']
 ['Jessica' '34']
 ['Jean' '21']
 ['Phoenix' '20']]


In [30]:
num_array = np.array([[1,3,5,7],[2,4,6,8]])
print(np.ndarray.flatten(num_array))

[1 3 5 7 2 4 6 8]


In [31]:
num = np.arange(1,13)
print(num, '\n')
new_num = num.reshape(3,4)
print(new_num)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
a = np.arange(1,6)
new_a = np.vstack(a)
print(a, a.shape)
print()
print(new_a, new_a.shape)
print()
print(a[0], new_a[0])

[1 2 3 4 5] (5,)

[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)

1 [1]


In [43]:
v1 = np.random.randint(2,8,4)
v2 = np.random.randint(3,9,4)
print(v1, v2, '\n')
print(np.vstack([v1, v2, v2, v1]))

[2 7 7 7] [6 4 8 6] 

[[2 7 7 7]
 [6 4 8 6]
 [6 4 8 6]
 [2 7 7 7]]


In [34]:
v3 = np.array([[4,4,5,5], [4,3,7,6]])
print(v3, '\n')
print(np.vstack([v3, v3]), '\n')
print(np.vstack([v3[1], v3[0]]))

[[4 4 5 5]
 [4 3 7 6]] 

[[4 4 5 5]
 [4 3 7 6]
 [4 4 5 5]
 [4 3 7 6]] 

[[4 3 7 6]
 [4 4 5 5]]


In [35]:
a = np.array([[1,4,6], [5,7,8]])
print(np.hstack(a))

[1 4 6 5 7 8]


In [36]:
h1 = np.array([[1,4,6], [5,7,8]])
h2 = np.array([[2,9,3], [17,31,26]])
print(np.hstack([h1, h2, h1]))

[[ 1  4  6  2  9  3  1  4  6]
 [ 5  7  8 17 31 26  5  7  8]]


In [37]:
for i in data_scientists:
    print(i)
print()
for i in data_scientists:
    for j in i:
        print(j)

['Charles' '18']
['Logan' '20']
['Jessica' '34']

Charles
18
Logan
20
Jessica
34
